blog/api/post/models.py
from flask_restplus import fields

from blog.api.post import post_api


comment_model = post_api.model("Comment", {
    "id": fields.Integer(readonly=True, description="Comment's ID", example=1),
    "user_id": fields.Integer(readonly=True, description="Comment's user",
                              example=1),
    "post_id": fields.Integer(readonly=True, description="Comment's post",
                              example=1),
    "body": fields.String(required=True, description="Comment's body",
                          example="Cool post!"),
    "datetime": fields.DateTime(readonly=True,
                                description="Comment's datetime",
                                example="2020-01-01T00:00:00.000000"),
    "likes": fields.Integer(description="Comment's likes count", readonly=True,
                            attribute=lambda x: x.likes_count(), example="0"),
    "dislikes": fields.Integer(description="Comment's dislikes count",
                               attribute=lambda x: x.dislikes_count(),
                               readonly=True, example="0"),
})

post_model = post_api.model("Post", {
    "id": fields.Integer(readonly=True, description="Post's ID", example=1),
    "user_id": fields.Integer(readonly=True, description="Post's user",
                              example=1),
    "title": fields.String(required=True, description="Post's title",
                           max_length=64, example="My first post"),
    "slug": fields.String(readonly=True, description="Post's slug",
                          example="my-first-post"),
    "body": fields.String(required=True, description="Post's body",
                          example="Hi, it's my first post!"),
    "created": fields.DateTime(readonly=True, description="Post's created",
                               example="2020-01-01T00:00:00.000000"),
    "likes": fields.Integer(description="Post's likes count", readonly=True,
                            attribute=lambda x: x.likes_count(), example="0"),
    "dislikes": fields.Integer(description="Post's dislikes count",
                               attribute=lambda x: x.dislikes_count(),
                               readonly=True, example="0"),
    "comments": fields.List(fields.Nested(comment_model),
                            readonly=True, description="Post's comments"),
})

blog/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class CommentForm(FlaskForm):
    """Form for creating comment"""

    body = StringField("Comment", validators=[DataRequired(), Length(min=10)])
    submit = SubmitField("Send")


class PostForm(FlaskForm):
    """Form for creating/editing post"""

    title = StringField("Title", validators=[DataRequired(), Length(max=64)])
    body = StringField("Body", validators=[DataRequired()])
    submit = SubmitField("Send")

blog/api/post/__init__.py
from flask_restplus import Namespace


post_api = Namespace("Posts", description="Blog posts", path="/post")


from blog.api.post import routes  # noqa: E402, F401

blog/api/post/routes.py
from flask import abort, request
from flask_restplus import Resource
from sqlalchemy.orm.exc import NoResultFound

from blog.api.auth import auth
from blog.api.post import post_api
from blog.api.post.models import comment_model, post_model
from blog.api.post.utils import (change_post, comment_post, create_post,
                                 delete_post, dislike_comment, dislike_post,
                                 get_all_posts, get_post, like_comment,
                                 like_post)


@post_api.route("/")
class PostList(Resource):
    """Actions with not specific post"""

    # Basic auth required for those actions
    decorators = [auth.login_required]

    @post_api.doc("post_list")
    @post_api.marshal_list_with(post_model, envelope="data")
    def get(self):
        """Get list of all posts"""

        return get_all_posts()

    @post_api.expect(post_model, validate=True)
    @post_api.marshal_with(post_model, code=201)
    @post_api.doc("create_post", responses={
        201: "Success",
        400: "Validation Error"
    })
    def post(self):
        """Create a new post"""

        return create_post(request.json), 201


@post_api.route("/<string:slug>")
@post_api.response(404, "Post not found")
@post_api.param("slug", "The post slug")
class Post(Resource):
    """Actions with specific post"""

    # Basic auth required for those actions
    decorators = [auth.login_required]

    @post_api.doc("get_post", responses={
        200: "Success",
    })
    @post_api.marshal_with(post_model)
    def get(self, slug):
        """Get post by slug"""

        try:
            return get_post(slug)
        except NoResultFound:
            return abort(404, "Post not found")

    @post_api.doc("delete_post")
    @post_api.response(204, "Post deleted")
    def delete(self, slug):
        """Delete post by slug"""

        delete_post(slug)
        return "", 204

    @post_api.expect(post_model, validate=True)
    @post_api.marshal_with(post_model)
    def put(self, slug):
        """Change post by slug"""

        data = request.json

        try:
            return change_post(slug, data)
        except NoResultFound:
            return abort(404, "Post not found")


@post_api.route("/<string:slug>/like")
@post_api.response(404, "Post not found")
@post_api.param("slug", "The post slug")
class PostLike(Resource):
    """Like a specific post"""

    @post_api.doc("like_post", responses={
        200: "Success",
    })
    @post_api.marshal_with(post_model)
    def get(self, slug):
        """Like a specific post"""

        try:
            return like_post(slug)
        except NoResultFound:
            return abort(404, "Post not found")


@post_api.route("/<string:slug>/dislike")
@post_api.response(404, "Post not found")
@post_api.param("slug", "The post slug")
class PostDislike(Resource):
    """Dislike a specific post"""

    @post_api.doc("dislike_post", responses={
        200: "Success",
    })
    @post_api.marshal_with(post_model)
    def get(self, slug):
        """Dislike a specific post"""

        try:
            return dislike_post(slug)
        except NoResultFound:
            return abort(404, "Post not found")


@post_api.route("/<string:slug>/comment")
@post_api.response(404, "Post not found")
@post_api.param("slug", "The post slug")
class PostComment(Resource):
    """Comment a specific post"""

    @post_api.expect(comment_model, validate=True)
    @post_api.marshal_with(post_model, code=201)
    @post_api.doc("comment_post", responses={
        201: "Success",
        400: "Validation Error"
    })
    def post(self, slug):
        """Comment a specific post"""

        try:
            return comment_post(slug, request.json), 201
        except NoResultFound:
            return abort(404, "Post not found")


@post_api.route("/comment/<int:comment_id>/like")
@post_api.response(404, "Comment not found")
@post_api.param("comment_id", "The comment identifier")
class CommentLike(Resource):
    """Like a specific comment"""

    @post_api.doc("like_comment", responses={
        200: "Success",
    })
    @post_api.marshal_with(comment_model)
    def get(self, comment_id):
        """Like a specific comment"""

        try:
            return like_comment(comment_id)
        except NoResultFound:
            return abort(404, "Comment not found")


@post_api.route("/comment/<int:comment_id>/dislike")
@post_api.response(404, "Comment not found")
@post_api.param("comment_id", "The comment identifier")
class CommentDislike(Resource):
    """Dislike a specific comment"""

    @post_api.doc("dislike_comment", responses={
        200: "Success",
    })
    @post_api.marshal_with(comment_model)
    def get(self, comment_id):
        """Dislike a specific comment"""

        try:
            return dislike_comment(comment_id)
        except NoResultFound:
            return abort(404, "Comment not found")

blog/post/__init__.py
from flask import Blueprint


bp = Blueprint("post", __name__)


from blog.post import routes  # noqa: E402, F401

blog/post/routes.py
from flask import flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from blog import db
from blog.post import bp
from blog.post.forms import CommentForm, PostForm
from blog.post.models import Comment, Post


@bp.route("/")
@login_required
def all_posts():
    """Show all posts"""

    # Page for pagination
    page = request.args.get("page", 1, type=int)
    # Posts with pagination
    posts = Post.query.order_by(Post.created.desc()).paginate(
        page, Post.POSTS_PER_PAGE, False
    )
    # Buttons for pagination
    next_url = url_for("post.all_posts", page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for("post.all_posts", page=posts.prev_num) \
        if posts.has_prev else None

    return render_template("post/index.html", posts=posts.items,
                           next_page=next_url, prev_page=prev_url,
                           current_page=page)


@bp.route("/<string:slug>", methods=["GET", "POST"])
@login_required
def view_post(slug: str):
    """Show post by slug"""

    post = Post.query.filter_by(slug=slug).first_or_404()

    form = CommentForm()

    if request.method == "POST" and form.validate_on_submit():
        comment = Comment()
        comment.body = form.body.data
        comment.user_id = current_user.id
        comment.post_id = post.id
        db.session.add(comment)
        db.session.commit()
        flash("You're successfully create the comment")
        return redirect(url_for("post.view_post", slug=slug))

    return render_template("post/view.html", post=post, comment_form=form)


@bp.route("/create", methods=["GET", "POST"])
@login_required
def create_post():
    """Create post"""

    form = PostForm()

    if request.method == "POST" and form.validate_on_submit():
        post = Post()
        form.populate_obj(post)
        post.user_id = current_user.id
        post.generate_slug()
        db.session.add(post)
        db.session.commit()
        flash("You're successfully create the post")
        return redirect(url_for("post.view_post", slug=post.slug))

    return render_template("post/form.html", form=form,
                           title="Create a new post")


@bp.route("/<string:slug>/edit", methods=["GET", "POST"])
@login_required
def edit_post(slug: str):
    """Edit post"""

    post = Post.query.filter_by(slug=slug).first_or_404()
    form = PostForm(obj=post)

    if request.method == "POST" and form.validate_on_submit():
        form.populate_obj(post)
        post.generate_slug()
        db.session.add(post)
        db.session.commit()
        flash("You're successfully edit the post")
        return redirect(url_for("post.view_post", slug=post.slug))

    return render_template("post/form.html", form=form,
                           title="Edit a post")


@bp.route("/<string:slug>/delete")
@login_required
def delete_post(slug: str):
    """Delete post"""

    post = Post.query.filter_by(slug=slug).first_or_404()
    db.session.delete(post)
    db.session.commit()
    flash("You're successfully delete the post")

    return redirect(url_for("post.all_posts"))


@bp.route("/<string:slug>/like")
@login_required
def like_post(slug: str):
    """Like post"""

    post = Post.query.filter_by(slug=slug).first_or_404()

    if not post.like(current_user.id):
        flash("You have unlike the post!")
    else:
        flash("You have like the post!")

    return redirect(url_for("post.view_post", slug=slug))


@bp.route("/<string:slug>/dislike")
@login_required
def dislike_post(slug: str):
    """Dislike post"""

    post = Post.query.filter_by(slug=slug).first_or_404()

    if not post.dislike(current_user.id):
        flash("You have undislike the post!")
    else:
        flash("You have dislike the post!")

    return redirect(url_for("post.view_post", slug=slug))


@bp.route("/<string:slug>/like/<int:comment_id>/like-comment")
@login_required
def like_comment(slug: str, comment_id: int):
    """Like comment"""

    comment = Comment.query.get_or_404(comment_id)

    if not comment.like(current_user.id):
        flash("You have unlike the comment!")
    else:
        flash("You have like the comment!")

    return redirect(url_for("post.view_post", slug=slug))


@bp.route("/<string:slug>/like/<int:comment_id>/dislike-comment")
@login_required
def dislike_comment(slug: str, comment_id: int):
    """Dislike comment"""

    comment = Comment.query.get_or_404(comment_id)

    if not comment.dislike(current_user.id):
        flash("You have undislike the comment!")
    else:
        flash("You have dislike the comment!")

    return redirect(url_for("post.view_post", slug=slug))

blog/templates/post/_comment.html
<li class="collection-item avatar">
    <a href="{{ url_for("post.view_post", slug=post.slug) }}">
        <img src="{{ post.user.avatar(42) }}"
             alt="{{ post.user.fullname }}"
             class="circle"
        >
    </a>
    {{ comment.body }}
    <a href="{{ url_for("post.dislike_comment",
                         slug=post.slug,
                         comment_id=comment.id) }}"
       class="secondary-content"
       style="right: 0; top: 44px;"
    >
        <span style="margin-left: 0; min-width:1rem;" class="badge">
            {{ comment.dislikes_count() }}
        </span>
        <i class="material-icons">thumb_down</i>
    </a>
    <a href="{{ url_for("post.like_comment",
                         slug=post.slug,
                         comment_id=comment.id) }}"
       class="secondary-content"
       style="right: 0;">
        <span style="margin-left: 0; min-width:1rem;" class="badge">
            {{ comment.likes_count() }}
        </span>
        <i class="material-icons">thumb_up</i>
    </a>
    <div style="color: #bdbdbd;">
        {{ comment.datetime.strftime('%Y-%m-%d %H:%M:%S') }}
    </div>
</li>

blog/templates/post/_post.html
<li class="collection-item avatar">
    <img src="{{ post.user.avatar(42) }}"
         alt="{{ post.user.fullname }}"
         class="circle"
    >
    <a href="{{ url_for("post.view_post", slug=post.slug) }}">
        <div class="title">{{ post.title }}</div>
    </a>
    {{ post.body }}
    <a class="secondary-content" style="right: 0; top: 44px;">
        <span style="margin-left: 0; min-width:1rem;" class="badge">
            {{ post.dislikes_count() }}
        </span>
        <i class="material-icons">thumb_down</i>
    </a>
    <a class="secondary-content" style="right: 0;">
        <span style="margin-left: 0; min-width:1rem;" class="badge">
            {{ post.likes_count() }}
        </span>
        <i class="material-icons">thumb_up</i>
    </a>
</li>

blog/templates/post/form.html
{% extends "base.html" %}
{% import "material/utils.html" as util %}
{% import "material/wtf.html" as wtf %}

{% block content %}
    {{ container() }}
        {{ row() }}
            {{ col(["s12", "offset-m3", "m6"]) }}
                {{ util.card(title, wtf.quick_form(form)) }}
            {{ enddiv() }}
        {{ enddiv() }}
    {{ enddiv() }}
{% endblock %}

blog/templates/post/index.html
{% extends "base.html" %}
{% import "material/utils.html" as util %}
{% import "material/wtf.html" as wtf %}

{% set post_list %}
    <ul class="collection">
        {% for post in posts %}
            {% include "post/_post.html" %}
        {% endfor %}
    </ul>
    {% set prev_active = "waves-effect" if prev_page else "disabled" %}
    {% set next_active = "waves-effect" if next_page else "disabled" %}
    <ul class="pagination center-align">
        <li class="{{ prev_active }}">
            <a href="{{ prev_page }}">
                <i class="material-icons">chevron_left</i>
            </a>
        </li>
        <li class="active"><a href="#">{{ current_page }}</a></li>
        <li class="{{ next_active }}">
            <a href="{{ next_page }}">
                <i class="material-icons">chevron_right</i>
            </a>
        </li>
    </ul>
{% endset %}

{% block content %}
    {{ container() }}
        {{ row() }}
            {{ col(["m12"]) }}
                {{ util.card("All posts", post_list) }}
            {{ enddiv() }}
        {{ enddiv() }}
    {{ enddiv() }}
    <div class="fixed-action-btn">
      <a href="{{ url_for("post.create_post") }}"
         class="btn-floating btn-large">
        <i class="large material-icons">create</i>
      </a>
    </div>
{% endblock %}

blog/templates/post/view.html
{% extends "base.html" %}
{% import "material/utils.html" as util %}
{% import "material/wtf.html" as wtf %}

{% set post_list %}
    <div class="row">
        <div class="col s12 m8">
            <h1 style="margin-top: 0;">{{ post.title }}</h1>
            {{ post.body }}
            <div class="right-align" style="color: #bdbdbd;">
                {{ post.created.strftime('%Y-%m-%d %H:%M:%S') }}
            </div>
            <ul class="collection">
                {% for comment in post.comments %}
                    {% include "post/_comment.html" %}
                {% endfor %}
            </ul>
            <h5>Add a comment</h5>
            {{ wtf.quick_form(comment_form) }}
        </div>
        <div class="col s12 m4 right-align">
            <div class="center-align">
                <img alt="{{ post.user.fullname }}"
                     src="{{ post.user.avatar(250) }}"
                >
                <h5 class="center-align">{{ post.user.fullname }}</h5>
                <a href="{{ url_for("post.dislike_post", slug=post.slug) }}"
                   class="secondary-content"
                   style="top: 44px;"
                >
                    <span style="margin-left: 0; min-width:1rem;"
                          class="badge"
                    >
                        {{ post.dislikes_count() }}
                    </span>
                    <i class="material-icons">thumb_down</i>
                </a>
                <a href="{{ url_for("post.like_post", slug=post.slug) }}"
                   class="secondary-content"
                >
                    <span style="margin-left: 0; min-width:1rem;"
                          class="badge"
                    >
                        {{ post.likes_count() }}
                    </span>
                    <i class="material-icons">thumb_up</i>
                </a>
            </div>
        </div>
    </div>
{% endset %}

{% block content %}
    {{ container() }}
        {{ row() }}
            {{ col(["m12"]) }}
                {{ util.card("", post_list) }}
            {{ enddiv() }}
        {{ enddiv() }}
    {{ enddiv() }}
    {% if current_user.id == post.user_id %}
        <div class="fixed-action-btn">
          <a href="{{ url_for("post.edit_post", slug=post.slug) }}"
             class="btn-floating btn-large">
            <i class="large material-icons">mode_edit</i>
          </a>
          <ul>
            <li>
                <a href="{{ url_for("post.delete_post", slug=post.slug) }}"
                   class="btn-floating red"
                >
                    <i class="material-icons">delete</i>
                </a>
            </li>
          </ul>
        </div>
    {% endif %}
{% endblock %}